# примеры API-запросов

@baseUrl = http://localhost:8000/api

# получение объявлений
GET {{baseUrl}}/advertisements/
Content-Type: application/json

###

# создание объявления
POST {{baseUrl}}/advertisements/
Content-Type: application/json
# User 1
Authorization: Token 22ec032da5a52d2030c243d5e9d188239a3d9c8e
# User 2
#Authorization: Token db9286856b8203155c55106faefcf1a4b848661f
# User Admin
#Authorization: Token 5d8cad9a39c777f715f4cfcfd22916c0a4347cd1

{
  "title": "Шкаф IKEA",
  "description": "Срочно"
}

###

# попытка поменять объявление
PATCH {{baseUrl}}/advertisements/2/
Content-Type: application/json
Authorization: Token 5d8cad9a39c777f715f4cfcfd22916c0a4347cd1

{
  "status": "DRAFT"
}

###
# Удаление объявления
DELETE {{baseUrl}}/advertisements/3/
Content-Type: application/json
Authorization: Token 5d8cad9a39c777f715f4cfcfd22916c0a4347cd1

###

# фильтрация по создателю
GET {{baseUrl}}/advertisements/?creator=2
Content-Type: application/json

###

# фильтрация по дате
GET {{baseUrl}}/advertisements/?created_at_before=2024-05-04
Content-Type: application/json