# Generated by Django 5.0.3 on 2024-04-09 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_remove_student_teacher_student_teacher'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='teacher',
            field=models.ManyToManyField(blank=True, related_name='students', to='school.teacher', verbose_name='Учителя'),
        ),
    ]
